export const themes = [
  { emoji: "💼", name: "Career" },
  { emoji: "❤️", name: "Relationships" },
  { emoji: "🌱", name: "Personal Growth" },
  { emoji: "💰", name: "Finance" },
  { emoji: "🏡", name: "Home & Family" },
  { emoji: "🧘", name: "Spirituality" },
];

export const questionsByTheme = {
  Career: [
    "🚀 What does my career path look like in the next six months?",
    "💼 How can I improve my leadership skills at work?",
    "🌟 What hidden talents should I leverage in my career?",
    "🎯 What steps should I take to achieve my professional goals?",
    "🤝 How can I build better relationships with my colleagues?",
    "📚 What new skills should I learn to advance in my field?",
  ],
  Relationships: [
    "❤️ How can I improve my current relationship?",
    "💕 What qualities should I look for in a potential partner?",
    "🗣️ How can I communicate better with my loved ones?",
    "🤗 What can I do to strengthen my friendships?",
    "💑 How can I maintain a healthy work-life balance?",
    "🚩 What red flags should I be aware of in my relationships?",
    "🛏️ When will I get laid?",
  ],
  "Personal Growth": [
    "🌱 What should I focus on for personal growth?",
    "🧠 How can I overcome my limiting beliefs?",
    "🏋️ What habits should I develop to improve my well-being?",
    "📚 What area of knowledge should I explore next?",
    "🎭 How can I become more authentic in my daily life?",
    "🧘 What practices can help me achieve inner peace?",
  ],
  Finance: [
    "💰 What energies surround my financial situation?",
    "💼 How can I increase my income in the next year?",
    "💳 What steps should I take to improve my financial stability?",
    "🏦 Is it a good time to make a major investment?",
    "📊 How can I better manage my expenses?",
    "🎯 What financial goals should I set for myself?",
  ],
  "Home & Family": [
    "🏡 Is it the right time to make a major life change?",
    "👨‍👩‍👧‍👦 How can I strengthen my family bonds?",
    "🏠 What can I do to create a more harmonious home environment?",
    "🌱 How can I support my children's growth and development?",
    "👵👴 How can I better care for my aging parents?",
    "🐾 Is it a good time to add a pet to our family?",
  ],
  Spirituality: [
    "🧘 What can I do to improve my spiritual well-being?",
    "🌟 How can I connect more deeply with my inner self?",
    "🙏 What spiritual practices would benefit me most?",
    "🌈 How can I align my actions with my spiritual beliefs?",
    "🕯️ What steps can I take to find more meaning in life?",
    "🌎 How can I contribute positively to the world around me?",
  ],
};
