const baseUrl = '/images/tarot/';

const tarotCardImages: { [key: string]: string } = {
  'The Fool': baseUrl + '00-TheFool.png',
  'The Magician': baseUrl + '01-TheMagician.png',
  'The High Priestess': baseUrl + '02-TheHighPriestess.png',
  'The Empress': baseUrl + '03-TheEmpress.png',
  'The Emperor': baseUrl + '04-TheEmperor.png',
  'The Hierophant': baseUrl + '05-TheHierophant.png',
  'The Lovers': baseUrl + '06-TheLovers.png',
  'The Chariot': baseUrl + '07-TheChariot.png',
  Strength: baseUrl + '08-Strength.png',
  'The Hermit': baseUrl + '09-TheHermit.png',
  'Wheel of Fortune': baseUrl + '10-WheelOfFortune.png',
  Justice: baseUrl + '11-Justice.png',
  'The Hanged Man': baseUrl + '12-TheHangedMan.png',
  Death: baseUrl + '13-Death.png',
  Temperance: baseUrl + '14-Temperance.png',
  'The Devil': baseUrl + '15-TheDevil.png',
  'The Tower': baseUrl + '16-TheTower.png',
  'The Star': baseUrl + '17-TheStar.png',
  'The Moon': baseUrl + '18-TheMoon.png',
  'The Sun': baseUrl + '19-TheSun.png',
  Judgement: baseUrl + '20-Judgement.png',
  'The World': baseUrl + '21-TheWorld.png',

  // Wands
  'Ace of Wands': baseUrl + 'Wands01.png',
  'Two of Wands': baseUrl + 'Wands02.png',
  'Three of Wands': baseUrl + 'Wands03.png',
  'Four of Wands': baseUrl + 'Wands04.png',
  'Five of Wands': baseUrl + 'Wands05.png',
  'Six of Wands': baseUrl + 'Wands06.png',
  'Seven of Wands': baseUrl + 'Wands07.png',
  'Eight of Wands': baseUrl + 'Wands08.png',
  'Nine of Wands': baseUrl + 'Wands09.png',
  'Ten of Wands': baseUrl + 'Wands10.png',
  'Page of Wands': baseUrl + 'Wands11.png',
  'Knight of Wands': baseUrl + 'Wands12.png',
  'Queen of Wands': baseUrl + 'Wands13.png',
  'King of Wands': baseUrl + 'Wands14.png',

  // Cups
  'Ace of Cups': baseUrl + 'Cups01.png',
  'Two of Cups': baseUrl + 'Cups02.png',
  'Three of Cups': baseUrl + 'Cups03.png',
  'Four of Cups': baseUrl + 'Cups04.png',
  'Five of Cups': baseUrl + 'Cups05.png',
  'Six of Cups': baseUrl + 'Cups06.png',
  'Seven of Cups': baseUrl + 'Cups07.png',
  'Eight of Cups': baseUrl + 'Cups08.png',
  'Nine of Cups': baseUrl + 'Cups09.png',
  'Ten of Cups': baseUrl + 'Cups10.png',
  'Page of Cups': baseUrl + 'Cups11.png',
  'Knight of Cups': baseUrl + 'Cups12.png',
  'Queen of Cups': baseUrl + 'Cups13.png',
  'King of Cups': baseUrl + 'Cups14.png',

  // Swords
  'Ace of Swords': baseUrl + 'Swords01.png',
  'Two of Swords': baseUrl + 'Swords02.png',
  'Three of Swords': baseUrl + 'Swords03.png',
  'Four of Swords': baseUrl + 'Swords04.png',
  'Five of Swords': baseUrl + 'Swords05.png',
  'Six of Swords': baseUrl + 'Swords06.png',
  'Seven of Swords': baseUrl + 'Swords07.png',
  'Eight of Swords': baseUrl + 'Swords08.png',
  'Nine of Swords': baseUrl + 'Swords09.png',
  'Ten of Swords': baseUrl + 'Swords10.png',
  'Page of Swords': baseUrl + 'Swords11.png',
  'Knight of Swords': baseUrl + 'Swords12.png',
  'Queen of Swords': baseUrl + 'Swords13.png',
  'King of Swords': baseUrl + 'Swords14.png',

  // Pentacles
  'Ace of Pentacles': baseUrl + 'Pentacles01.png',
  'Two of Pentacles': baseUrl + 'Pentacles02.png',
  'Three of Pentacles': baseUrl + 'Pentacles03.png',
  'Four of Pentacles': baseUrl + 'Pentacles04.png',
  'Five of Pentacles': baseUrl + 'Pentacles05.png',
  'Six of Pentacles': baseUrl + 'Pentacles06.png',
  'Seven of Pentacles': baseUrl + 'Pentacles07.png',
  'Eight of Pentacles': baseUrl + 'Pentacles08.png',
  'Nine of Pentacles': baseUrl + 'Pentacles09.png',
  'Ten of Pentacles': baseUrl + 'Pentacles10.png',
  'Page of Pentacles': baseUrl + 'Pentacles11.png',
  'Knight of Pentacles': baseUrl + 'Pentacles12.png',
  'Queen of Pentacles': baseUrl + 'Pentacles13.png',
  'King of Pentacles': baseUrl + 'Pentacles14.png',
};

export default tarotCardImages;
